.PHONY: test-core test-mm

all:
	$(MAKE) run -C test-core
	$(MAKE) run -C test-mm

test-core:
	$(MAKE) run -C test-core

test-mm:
	$(MAKE) run -C test-mm

clean:
	$(MAKE) clean -C test-core
	$(MAKE) clean -C test-mm
