FROM debian:9
MAINTAINER simon@brennecke-it.net
RUN export http_proxy=http://147.204.6.136:8080; apt-get update && apt-get install --no-install-recommends -y git g++ clang tar make cmake unzip llvm-dev valgrind libedit-dev zlib1g-dev

