FROM debian:unstable
MAINTAINER simon@brennecke-it.net
CMD apt-get update && apt-get install -y --no-install-recommends llvm && dpkg -i /infrabox/inputs/$COMPILE_CONTAINER/libcl3-core.deb /infrabox/inputs/$COMPILE_CONTAINER/libcl3-core-tests.deb && cd /opt/cl3 && /usr/local/bin/cl3-core-test --gtest_output=xml:gtest.native.xml dummy1 dummy2 dummy3
