FROM debian:unstable
MAINTAINER simon@brennecke-it.net
RUN apt-get update && apt-get install --no-install-recommends -y git g++ clang tar make cmake lcov python unzip llvm-dev valgrind libedit-dev zlib1g-dev

