#!/bin/bash

for ((m=2;m<=16;m++)); do
	echo -n "template<class A1"
	for ((i=2;i<$m;i++)); do
		echo -n ", class A$i"
	done
	echo ">"
	echo -n "CLASS	TRefCounter(A1 a1"
	for ((i=2;i<$m;i++)); do
		echo -n ", A$i a$i"
	done
	echo -n ") : n_refs(0), object(a1"
	for ((i=2;i<$m;i++)); do
		echo -n ", a$i"
	done
	echo ") {}"
	echo
done
